version: '3'

services:

  redis:
    image: 'redis:5.0.5'
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default

  cassandra:
    image: 'cassandra:3.11.4'
    restart: always
    ports:
      - '9042:9042'
    networks:
      - default
    volumes:
      - /var/data/advisor/cassandra:/var/lib/cassandra
      - ./cassandra/db-init-scripts:/docker-entrypoint-initdb.d
    command: "sh /docker-entrypoint-initdb.d/cassandra-init.sh"

  nginx:
    build:
      dockerfile: Dockerfile
      context: nginx
    restart: always
    ports:
      - '3051:80'
    networks:
      - default
    depends_on:
      - advisor
      - advisor-auth
      - frontend

  config-server:
    build:
      context: advisor-config-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8888:8888'
    networks:
      - default
    volumes:
      - maven-repo:/root/.m2
      - ./advisor-config-server:/app
    depends_on:
      - redis
    command: ["./wait-for-it.sh", "redis:6379", "--", "mvn", "spring-boot:run"]

  discovery-server:
    build:
      context: advisor-discovery-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '9777:9777'
    networks:
      - default
    volumes:
      - maven-repo:/root/.m2
      - ./advisor-discovery-server:/app
    depends_on:
      - config-server
    command: ["./wait-for-it.sh", "config-server:8888", "--", "mvn", "spring-boot:run"]

  security-core:
    build:
      context: security-core
      dockerfile: Dockerfile
    volumes:
      - maven-repo:/root/.m2

  advisor:
    build:
      context: advisor-service
      dockerfile: Dockerfile
    ports:
      - '9888:9888'
    networks:
      - default
    volumes:
      - maven-repo:/root/.m2
      - ./advisor-service:/app
    depends_on:
      - redis
      - config-server
      - discovery-server
    command: ["./wait-for-it.sh", "discovery-server:9777", "--", "mvn", "clean", "compile", "spring-boot:run"]


  advisor-auth:
      build:
        context: advisor-auth-service
        dockerfile: Dockerfile
      ports:
        - '9666:9666'
      networks:
        - default
      volumes:
        - maven-repo:/root/.m2
        - ./advisor-auth-service:/app
      depends_on:
        - security-core
        - config-server
        - discovery-server
        - cassandra
      command: ["./wait-for-it.sh", "discovery-server:9777", "--", "mvn", "clean", "compile", "spring-boot:run"]

  frontend:
    build:
      context: advisor-frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    networks:
      - default
    volumes:
      - /app/node_modules
      - ./advisor-frontend:/app


networks:
  default:
    external:
      name: advisor-net

volumes:
  maven-repo:

