version: '3'

services:

  config-server:
    build:
      context: advisor-config-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - maven-repo:/root/.m2

  discovery-server:
    build:
      context: advisor-discovery-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '9777:9777'
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      - config-server
    command: ["./wait-for-it.sh", "config-server:8888", "--", "mvn", "clean", "compile", "spring-boot:run"]

  advisor:
    build:
      context: advisor-service
      dockerfile: Dockerfile
#    restart: always
    ports:
      - '9888:9888'
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      - config-server
      - discovery-server
    command: ["./wait-for-it.sh", "discovery-server:9777", "--", "mvn", "clean", "compile", "spring-boot:run"]

volumes:
  maven-repo: